en:
  - "I am going to home."
  - "He do not like it."
  - "She is more tall than me."
  - "I have been to there yesterday."
  - "They was happy."
  - "Can I have a water?"
  - "He gave to me the book."
  - "I'm very interesting in this."
  - "She explained me the problem."
  - "I want to discuss about the issue."

es:
  - "Yo soy va a casa."
  - "Él no le gusta."
  - "Ella es más alta que yo."
  - "He estado allí ayer."
  - "Ellos estaba felices."
  - "¿Puedo tener un agua?"
  - "Él me dio a mí el libro."
  - "Estoy muy interesante en esto."
  - "Ella me explicó a mí el problema."
  - "Quiero discutir sobre el tema."
