"""The three entitlement tables and the two native enums the grant table binds. Allowance is derived from the tier."""
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any, cast
from uuid import UUID, uuid7

from sqlalchemy import DateTime, Enum
from sqlmodel import Field, SQLModel


class AccessGrantSource(StrEnum):
    """Mirrors `core.access_grant_source`. Only `subscription` carries a `subscription_id`."""
    subscription = "subscription"
    anonymous_device_grant = "anonymous_device_grant"
    registered_account_grant = "registered_account_grant"
    manual = "manual"


class AccessGrantStatus(StrEnum):
    """Mirrors `core.access_grant_status`. Revoked and expired rows stay in place as history."""
    active = "active"
    revoked = "revoked"
    expired = "expired"


AccessGrantSourceType = cast(Any, Enum(AccessGrantSource, name='access_grant_source', schema='core'))
AccessGrantStatusType = cast(Any, Enum(AccessGrantStatus, name='access_grant_status', schema='core'))
DateTimeType = cast(Any, DateTime(timezone=True))


class AccessTier(SQLModel, table=True):
    """One allowance tier. Seeded reference data -- three rows, written by the migration."""

    __tablename__ = "access_tiers"
    __table_args__ = {"schema": "core"}

    # No default_factory: tier ids are seeded by the migration, never generated by the application.
    id: str = Field(primary_key=True)
    monthly_credits: int = Field()
    created_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))


# The table's four GENERATED ALWAYS AS STORED columns are deliberately unmapped: Postgres rejects an explicit value.
class AccessGrant(SQLModel, table=True):
    """One entitlement held by one user, resolved against a tier for its allowance."""

    __tablename__ = "access_grants"
    __table_args__ = {"schema": "core"}

    id: UUID = Field(default_factory=uuid7, primary_key=True)
    user_id: UUID = Field(foreign_key="core.users.id")
    tier_id: str = Field(foreign_key="core.access_tiers.id")
    source: AccessGrantSource = Field(sa_type=AccessGrantSourceType)
    status: AccessGrantStatus = Field(sa_type=AccessGrantStatusType, default=AccessGrantStatus.active)
    # A database CHECK enforces the agreement with `source` in both directions.
    subscription_id: UUID | None = Field(default=None)
    starts_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
    ends_at: datetime | None = Field(sa_type=DateTimeType, default=None)
    created_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))


class UserMonthlyUsage(SQLModel, table=True):
    """Consumption for one grant in one UTC calendar month. The grant id *is* the primary key."""

    __tablename__ = "user_monthly_usage"
    __table_args__ = {"schema": "core"}

    grant_id: UUID = Field(foreign_key="core.access_grants.id", primary_key=True)
    # Free text in YYYY-MM; the database enforces no format.
    monthly_period: str = Field()
    monthly_used: int = Field(default=0)
    # NOT NULL with no database DEFAULT, unlike every other table: these factories are the only source of a value.
    created_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
