"""The three entitlement tables -- `core.access_tiers`, `core.access_grants`,
`core.user_monthly_usage` -- and the two native enums the grant table binds.

`core.access_tiers` is seeded reference data, not generated rows: the initial migration INSERTs
`anonymous` (10 credits), `registered` (50) and `paid` (1000), so `AccessTier.id` carries no
default factory. An allowance is never stored on a grant or on a usage row; it is derived by
joining the grant to its tier.

`core.user_monthly_usage` is keyed on `grant_id`, not on a user, and replaces the dropped
`core.usage_monthly` that `models/users.py` records as gone. Its `created_at`/`updated_at` are
`NOT NULL` with **no** database DEFAULT, unlike every other table in the schema, so the
`default_factory` on those two fields is load-bearing rather than decorative: drop it and every
insert fails on a NOT NULL violation.

Four columns of `core.access_grants` are deliberately absent, for one shared reason:

- `anti_abuse_required_grant_id`
- `active_registered_account_grant_id`
- `active_subscription_grant_subscription_id`
- `active_subscription_grant_user_id`

All four are `GENERATED ALWAYS AS (...) STORED`. PostgreSQL rejects an explicit value for a
generated column, so a mapped field would turn every ORM insert or update into an error the moment
SQLAlchemy emitted the column. They exist only as the composite FK and index targets the migration
declares; nothing in Python reads or writes them. No SQLModel class in this repo maps a generated
column, and this one does not become the first.

The database owns every constraint. `access_tiers`' `monthly_credits >= 0`, `access_grants`'
`ends_at > starts_at` and subscription_id/source agreement CHECKs, `user_monthly_usage`'s
`monthly_used >= 0`, the `UNIQUE (id, source)` composite FK target, the two deferrable
subscription FKs, the `ON DELETE CASCADE` on both `user_id` and `grant_id`, and the partial unique
indexes -- `ix_access_grants_one_per_subscription` and, in particular,
`ix_access_grants_one_active_per_user`, which is a plain non-deferrable per-statement index and is
what makes "at most one active grant per user" true -- are all declared in
`migrations/20260818_01_initial-release.sql` and are deliberately not re-encoded here: a Python
copy of a CHECK is a second source of truth that can drift from the one that actually enforces.
"""
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any, cast
from uuid import UUID, uuid7

from sqlalchemy import DateTime, Enum
from sqlmodel import Field, SQLModel


class AccessGrantSource(StrEnum):
    """Mirrors `core.access_grant_source`. Exactly four values.

    `subscription` is the only source that carries a `subscription_id`; the other three forbid
    it. `manual` names whichever tier the issuance chooses rather than having a tier of its own.
    There is no `promo` -- ruling 9.1 deleted it from the enum and from every rule referencing it.
    """
    subscription = "subscription"
    anonymous_device_grant = "anonymous_device_grant"
    registered_account_grant = "registered_account_grant"
    manual = "manual"


class AccessGrantStatus(StrEnum):
    """Mirrors `core.access_grant_status`. Exactly three values.

    Only `active` participates in `ix_access_grants_one_active_per_user`; `revoked` and `expired`
    rows stay in place as history, which is how a superseded grant remains readable after a claim.
    """
    active = "active"
    revoked = "revoked"
    expired = "expired"


AccessGrantSourceType = cast(Any, Enum(AccessGrantSource, name='access_grant_source', schema='core'))
AccessGrantStatusType = cast(Any, Enum(AccessGrantStatus, name='access_grant_status', schema='core'))
DateTimeType = cast(Any, DateTime(timezone=True))


class AccessTier(SQLModel, table=True):
    """One allowance tier. Seeded reference data -- three rows, written by the migration."""

    __tablename__ = "access_tiers"
    __table_args__ = {"schema": "core"}

    # No default_factory: tier ids are seeded reference data written by the migration, never
    # generated by the application. Same no-default primary-key shape as models/chats.py:38.
    id: str = Field(primary_key=True)
    monthly_credits: int = Field()
    created_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))


class AccessGrant(SQLModel, table=True):
    """One entitlement held by one user, resolved against a tier for its allowance."""

    __tablename__ = "access_grants"
    __table_args__ = {"schema": "core"}

    id: UUID = Field(default_factory=uuid7, primary_key=True)
    # ON DELETE CASCADE in the migration -- deleting a user takes its grants with it.
    user_id: UUID = Field(foreign_key="core.users.id")
    tier_id: str = Field(foreign_key="core.access_tiers.id")
    source: AccessGrantSource = Field(sa_type=AccessGrantSourceType)
    status: AccessGrantStatus = Field(sa_type=AccessGrantStatusType, default=AccessGrantStatus.active)
    # Set exactly when source is 'subscription'; a database CHECK enforces the agreement in both
    # directions, so no free or manual grant can be written as a fake subscription.
    subscription_id: UUID | None = Field(default=None)
    starts_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
    # Open-ended grants are legal (ruling 9.11), so a finite end is never required.
    ends_at: datetime | None = Field(sa_type=DateTimeType, default=None)
    created_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))


class UserMonthlyUsage(SQLModel, table=True):
    """Consumption for one grant in one UTC calendar month. The grant id *is* the primary key."""

    __tablename__ = "user_monthly_usage"
    __table_args__ = {"schema": "core"}

    grant_id: UUID = Field(foreign_key="core.access_grants.id", primary_key=True)
    # Free text in YYYY-MM with no format CHECK in the database (00-schema.md:500) -- do not
    # invent one here either.
    monthly_period: str = Field()
    monthly_used: int = Field(default=0)
    # These two columns are NOT NULL with no database DEFAULT, unlike every other table in the
    # schema. The factories are the only thing supplying a value.
    created_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(sa_type=DateTimeType, default_factory=lambda: datetime.now(UTC))
