apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ns-api-gateway.fullname" . }}-llm-routes
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ns-api-gateway.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /chats
      method: POST
    backendRefs:
    - name: {{ include "ns-api-gateway.fullname" . }}
      port: {{ .Values.service.port }}
