apiVersion: v1
kind: Service
metadata:
  name: {{ include "ns-api-gateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ns-api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "ns-api-gateway.selectorLabels" . | nindent 4 }}
